### ISSUE TITLE
md5 Mismatch

### ISSUE THREAD

**Issue by Fishqt** [notwa/boorubot#1]
Hey there!

I see it's been quite a while since you updated this script, but I hope you're still able to help me out.

I'm looking to start a worksafe bot using your script, but I'm getting error messages every time I try to post something.

`~/boorubot$ python3.5 boorubot.py -a CuteBooru -q 'order:score rating:safe' -o safe
md5 mismatch between 93e6d0d665c373bd6c5c9df8088b501e and desired __original_and_queen_band_drawn_by_riyo_lyomsnpmp__93e6d0d665c373bd6c5c9df8088b501e
md5 mismatch between d77a5df684ece28477501bf668887bc8 and desired __casper_and_windia_deathsmiles_drawn_by_ookuma_nitroplus__d77a5df684ece28477501bf668887bc8
md5 mismatch between 8255681cbea6adfb340de394fba5402b and desired __hatsune_miku_kagamine_rin_and_megurine_luka_vocaloid_drawn_by_wokada__8255681cbea6adfb340de394fba5402b
`

As you can see, it seems it isn't pleased with the checksum of the images it tries to fetch.

Got any ideas, or is there a way to make the script ignore checksumming?

Thanks!

**Comment by notwa** [comment]
yes hello
this is an issue because danbooru started including tags in filenames; they used to just be the md5sum as the script expects. i can fix this in a bit.
